- name: installing ngnix server
  hosts: mongodb
  become: yes
  tasks:
  - name: Install ngnix
    ansible.builtin.yum:
     name: ngnix
     state: installed
  - name: Start nginx
    ansible.builtin.service:  
     name: nginx
     state: started
