- name: Variables
  hosts: mongodb
  vars_files:
  - variables.yaml
  tasks:
  - name: Printing variables from file
    ansible.builtin.debug:
     msg: "Tutor is {{Tutor}}, Course is {{Course}}, Duration is {{Duration}}"
