- name: Varibles from prompt
  hosts: mongodb
  vars_prompt:
  - name: Username
    prompt: Enter your Username
    private: false
  - name: Password
    prompt: Enter Your password
    private: true

  tasks:
  - name: Print Varibles
    ansible.builtin.debug:
     msg: "Entered username : {{Username}}, Entered Password : {{Password}}"   