- name: Loops creation
  hosts: mongodb

  tasks:
  - name: printing basic details
    ansible.builtin.debug:
     msg: "printing Name: {{item.Name}}, Age :{{item.age}} " 


    loop:
    - {Name: Shiva, age: 35}
    - {Name: Arun, age: 30}
    - {Name: Raj, age: 20}